# Generated by Django 2.1.7 on 2019-02-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='count_col',
            field=models.CharField(default=0, max_length=2000),
        ),
        migrations.AlterModelTable(
            name='mymodel',
            table='Product',
        ),
    ]
