# Generated by Django 2.1.7 on 2019-02-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_auto_20190219_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='count_col',
            field=models.CharField(default='aaa', max_length=2000),
        ),
    ]
